DEFAULT_PORT = 3001
DEFAULT_WINDOW_WIDTH = 1200
DEFAULT_WINDOW_HEIGHT = 800

API_BASE_PATH = "/api"
API_DOCS_PATH = f"{API_BASE_PATH}/docs"
API_GRAPH_PATH = f"{API_BASE_PATH}/graph"
API_SEARCH_PATH = f"{API_BASE_PATH}/search"

FRONTEND_DIST_PATH = "frontend/dist"

APP_TITLE = "DocViewer Demo"
APP_VERSION = "1.0.0"

SEARCH_THRESHOLD = 0.4
SEARCH_LIMIT = 10

GRAPH_LAYOUT_DEFAULT = "cose"
GRAPH_NODE_SIZE = 50
GRAPH_EDGE_WIDTH = 2